name: Anilist Readme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Anilist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pxseu/anilist-readme@v1.4.2
        with:
          # Your anilist user id
          user_id: 5492163
          gh_token: ${{ secrets.GH_TOKEN }}
          timezone: "Europe/Belgrade"
          date_format: "{h}:{m} {D}-{MW}-{Y}"
