name: Update README with readme-scribe

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme-markscribe:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Readme-scribe Action
        uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          template: "README.md.tpl"
          writeTo: "READMEnew.md"

      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: 📋 Update README with Detailed activity
          branch: master
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

      - name: Copy-Paste Action
      - uses: ShreyamMaity/Copy-Paste-Action@V2.0
        with:
          TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          REPOSITORY : 'momcilovicluka'
          COPY-FILE-LOCATION : './READMEnew.md'
          PASTE-FILE-LOCATION : './README.md'
            
