name: Update README with github-activity-readme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          MAX_LINES: 5
          COMMIT_NAME:	github-actions[bot]
          COMMIT_EMAIL:	41898282+github-actions[bot]@users.noreply.github.com
          COMMIT_MSG:	⚡ Update README with recent activity
