name: Update README with waka-readme-stats

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme-wakatime:
    name: Update Readme with WakaTime Metrics
    runs-on: ubuntu-latest
    steps:
      - name: WakaTime Action
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LOC_CHART: "False"
          LOCALE: "en"
          COMMIT_MESSAGE: "⌚ Update README with WakaTime activity"
          COMMIT_USERNAME: "github-actions[bot]"
          COMMIT_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
